backend:
  name: git-gateway
  branch: main
media_folder: 'assets/img'
collections:
  - name: 'pages'
    label: 'Pages'
    editor:
      preview: false
    files:
      - label: 'Fellowships & Awards'
        name: 'awards'
        file: '_data/awards.yml'
        fields:
          - label: 'Awards'
            name: 'items'
            widget: 'list'
            fields:
              - label: 'Name'
                name: 'name'
                widget: 'string'
              - label: 'Year'
                name: 'year'
                widget: 'string'
      - label: 'Certificates & Affiliations'
        name: 'certs'
        file: '_data/certs.yml'
        fields:
          - label: 'Certificates'
            name: 'certs'
            widget: 'list'
            field: { label: 'Name', name: 'name', widget: 'string' }
            summary: '{{fields.name}}'
          - label: 'Affiliations'
            name: 'affiliations'
            widget: 'list'
            field: { label: 'Name', name: 'name', widget: 'string' }
            summary: '{{fields.name}}'
      - label: 'Education'
        name: 'education'
        file: '_data/education.yml'
        fields:
          - label: 'Education'
            name: 'items'
            widget: 'list'
            summary: '{{fields.degree}} @ {{fields.school}}'
            fields:
              - label: 'Year'
                name: 'year'
                widget: 'number'
                min: 1900
                max: 2100
              - label: 'Degree'
                name: 'degree'
                widget: 'string'
              - label: 'School'
                name: 'school'
                widget: 'string'
              - label: 'Location'
                name: 'location'
                widget: 'string'
              - label: 'Description'
                name: 'description'
                widget: 'text'
                required: false
          - label: 'Areas of Scholarly Research'
            name: 'research'
            widget: 'list'
            field: { label: 'Name', name: 'name', widget: 'string' }
            summary: '{{fields.name}}'
      - label: 'Exhibitions'
        name: 'exhibitions'
        file: '_data/exhibitions.yml'
        fields:
          - label: 'Exhibitions'
            name: 'items'
            widget: 'list'
            fields:
              - label: 'Title'
                name: 'title'
                widget: 'string'
              - label: 'Location'
                name: 'location'
                widget: 'string'
              - label: 'Year'
                name: 'year'
                widget: 'string'
      - label: 'Teaching Experience'
        name: 'experience'
        file: '_data/experience.yml'
        fields:
          - label: 'Teaching Experience'
            name: 'items'
            widget: 'list'
            summary: '{{fields.title}} @ {{fields.location}}'
            fields:
              - label: 'Year'
                name: 'year'
                widget: 'string'
              - label: 'Title'
                name: 'title'
                widget: 'string'
              - label: 'Location'
                name: 'location'
                widget: 'string'
          - label: 'Courses Taught'
            name: 'courses'
            widget: 'object'
            fields:
              - label: 'Graduate'
                name: 'Graduate'
                widget: 'list'
                summary: '{{fields.code}}: {{fields.name}}'
                fields:
                  - { label: 'Code', name: 'code', widget: 'string' }
                  - { label: 'Name', name: 'name', widget: 'string' }
                  - { label: 'Location', name: 'location', widget: 'string' }
              - label: 'Undergraduate'
                name: 'Undergraduate'
                widget: 'list'
                summary: '{{fields.code}}: {{fields.name}}'
                fields:
                  - { label: 'Code', name: 'code', widget: 'string' }
                  - { label: 'Name', name: 'name', widget: 'string' }
                  - { label: 'Location', name: 'location', widget: 'string' }
              - label: 'Distance Education-Online Courses'
                name: 'Distance Education-Online Courses'
                widget: 'list'
                summary: '{{fields.code}}: {{fields.name}}'
                fields:
                  - { label: 'Code', name: 'code', widget: 'string' }
                  - { label: 'Name', name: 'name', widget: 'string' }
                  - { label: 'Location', name: 'location', widget: 'string' }
      - label: 'Publications'
        name: 'publications'
        file: '_data/publications.yml'
        fields:
          - label: 'Books'
            name: 'books'
            widget: 'list'
            fields: 
              - { label: 'Name', name: 'name', widget: 'string' }
              - { label: 'URL', name: 'url', widget: 'string' }
          - label: 'Exhibition Catalogues'
            name: 'exhibition-catalogues'
            widget: 'list'
            field: { label: 'Name', name: 'name', widget: 'string' }
            summary: '{{fields.name}}'
          - label: 'Articles'
            name: 'articles'
            widget: 'list'
            field: { label: 'Name', name: 'name', widget: 'string' }
            summary: '{{fields.name}}'
          - label: 'Book Chapters'
            name: 'book-chapters'
            widget: 'list'
            field: { label: 'Name', name: 'name', widget: 'string' }
            summary: '{{fields.name}}'
          - label: 'Reviews'
            name: 'reviews'
            widget: 'list'
            field: { label: 'Name', name: 'name', widget: 'string' }
            summary: '{{fields.name}}'
          - label: 'Encyclopedias'
            name: 'encyclopedias'
            widget: 'list'
            field: { label: 'Name', name: 'name', widget: 'string' }
            summary: '{{fields.name}}'
